version: "3.2"

services:
  dev:
    container_name: es_editor_dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    tty: true
    volumes:
      - type: volume
        source: develop_volume
        target: /root/
    ports:
      - 3000:3000

  # ローカルにgit cloneしておく必要有り
  prod:
    container_name: es_editor_prod
    build:
      context: .
      dockerfile: prod.Dockerfile
    tty: true
    ports:
      - 4125:3000

volumes:
  develop_volume: