version: "3.4"

services:
  prod_front:
    container_name: es_editor_prod_front
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
        - NEXT_PUBLIC_GA_TRACKING_ID=$NEXT_PUBLIC_GA_TRACKING_ID
    tty: true
    profiles:
      - prod
    ports:
      - 3000:3000
    env_file:
      - .env
      - .env.secret

  prod_back:
    container_name: es_editor_prod_back
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    tty: true
    profiles:
      - prod
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
      - .env.secret

  dev_front:
    container_name: es_editor_dev_front
    build:
      context: .
      dockerfile: ./frontend/dev.Dockerfile
    tty: true
    profiles:
      - dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /root/app
    env_file:
      - .env
      - .env.development
      - .env.secret

  dev_back:
    container_name: es_editor_dev_back
    build:
      context: .
      dockerfile: ./backend/dev.Dockerfile
    tty: true
    profiles:
      - dev
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: .
        target: /root/app
    env_file:
      - .env
      - .env.development
      - .env.secret

  db:
    container_name: es_editor_db
    build:
      context: ./db
    tty: true
    volumes:
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./db/DATA
        target: /var/lib/mysql
    profiles:
      - dev
      - prod
    healthcheck:
      test: "mysql --password=${MARIADB_ROOT_PASSWORD} --execute 'show databases;'"
      interval: 3s
      timeout: 30s
      retries: 10
      start_period: 0s
    env_file:
      - .env
      - .env.secret
