version: "3.2"

services:
  # ローカルにgit cloneしておく必要有り
  prod_front:
    container_name: es_editor_prod_front
    build:
      context: ./frontend 
      dockerfile: prod.Dockerfile
    tty: true
    ports:
      - 4125:3000

  dev:
    container_name: es_editor_dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    tty: true
    volumes:
      - type: volume
        source: develop_volume
        target: /root/
    ports:
      - 3000:3000

volumes:
  develop_volume: