version: "3.4"

services:
  # 本番フロントエンド
  prod_front:
    container_name: es_editor_prod_front
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    tty: true
    profiles:
      - prod
    ports:
      - 3000:3000
    env_file:
      - .env

  # 本番バックエンド(仮)
  prod_back:
    container_name: es_editor_prod_back
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    tty: true
    profiles:
      - prod
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  # 開発フロントエンド
  dev_front:
    container_name: es_editor_dev_front
    build:
      context: .
      dockerfile: ./frontend/dev.Dockerfile
    tty: true
    profiles:
      - dev
    ports:
      - 3000:3000
    volumes:
      - type: volume
        source: git_clone
        target: /root/es-editor
    env_file:
      - .env

  # 開発バックエンド
  dev_back:
    container_name: es_editor_dev_back
    build:
      context: .
      dockerfile: ./backend/dev.Dockerfile
    tty: true
    environment:
      - FLASK_APP=flaskr
    profiles:
      - dev
    ports:
      - 5000:5000
    volumes:
      - type: volume
        source: git_clone
        target: /root/es-editor
    env_file:
      - .env

  # データベース
  db:
    container_name: es_editor_db
    build:
      context: ./db
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d
    profiles:
      - dev
      - prod
    healthcheck:
      test: "mysql --password=${MYSQL_ROOT_PASSWORD} --execute 'show databases;'"
      interval: 3s
      timeout: 30s
      retries: 10
      start_period: 0s
    env_file:
      - .env

  git_clone:
    container_name: es_editor_git_clone
    build:
      context: .
      dockerfile: gitclone.Dockerfile
    volumes:
      - type: volume
        source: git_clone
        target: /root/es-editor
    profiles:
      - none
    env_file:
      - .env

volumes:
  git_clone:
