version: "3.2"

services:
  # ローカルにgit cloneしておく必要有り
  prod_front:
    container_name: es_editor_prod_front
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    tty: true
    profiles:
      - prod
    ports:
      - 3000:3000

  # ローカルにgit cloneしておく必要有り
  prod_back:
    container_name: es_editor_prod_back
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    tty: true
    profiles:
      - prod
    ports:
      - 5000:5000

  dev_front:
    container_name: es_editor_dev_front
    build:
      context: .
      dockerfile: ./frontend/dev.Dockerfile
    tty: true
    profiles:
      - dev
    ports:
      - 3000:3000

  dev_back:
    container_name: es_editor_dev_back
    build:
      context: .
      dockerfile: ./backend/dev.Dockerfile
    tty: true
    profiles:
      - dev
    ports:
      - 5000:5000