version: "3.2"

services:
  nextjs:
    container_name: nextjs
    build:
      context: ..
      dockerfile: ./frontend/dev.Dockerfile
    tty: true
    volumes:
      - type: volume
        source: develop_volume
        target: /root/
    ports:
      - 3000:3000
  flask:
    container_name: flask
    build:
      context: ..
      dockerfile: ./backend/dev.Dockerfile
    tty: true
    ports:
      - 5000:5000

volumes:
  develop_volume:
