name: backend_pytest

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: copy .env.template
        shell: bash
        run: cp .env.secret.template .env.secret
      
      - name: start db
        shell: bash
        run: docker-compose up db

      - name: execute pytest
        shell: bash
        run: docker-compose run prod_back bash -c "poetry run python -m pytest"
