name: backend_pytest

on:
  push:
    branches:
      - kaji/test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker-compose db, backend
        shell: bash
        run: docker-compose up -d db prod_back

      - name: pytest
        shell: bash
        run: docker-compose exec -T prod_back sh -c 'pytest'
