name: backend_pytest

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: copy .env.template
        shell: bash
        run: cp .env.secret.template .env.secret && mkdir ./db/DATA

      - name: docker-compose db, backend
        shell: bash
        run: docker-compose up -d db prod_back

      - name: pytest
        shell: bash
        run: docker-compose exec -T prod_back sh -c 'pytest'
